cloud:
  aws:
    credentials:
      profileName:
      instanceProfile: false
    region:
      auto: false
      static: ap-northeast-1
rds:
  identifier: ${RDS_IDENTIFIER:mynavi-sample-db}
  password: ${RDS_PASSWORD:postgresql}